callback_params:
  - name: EarlyStopping
    args:
      patience: 3
  - name: ModelCheckpoint
    args:
      monitor: "val_loss"
      mode: "min"
      dirpath: "data/06_models/checkpoints"
      filename: "best-model"
      save_top_k: 1

train_hparams:
  accelerator: auto
  learning_rate: 0.003
  epochs: 5
  precision: "32"

data_loaders_params:
  train_path: None
  val_path: None
  batch_size: 64